config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "static_pages#top"
  get "explanation", to: "static_pages#explanation"
  get "privacy_policy", to: "static_pages#privacy"
  get "terms_of_service", to: "static_pages#condition"

  resources :contacts, only: [:new, :create]
  
  get 'user_top', to: 'homes#top'

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resource :profile, only: %i[edit update show]
  resources :recipes, only: %i[index new create edit show update destroy] do
    collection do
      get :create_index
    end
  end
  namespace :openai do
    get 'ask_question', to: 'change#ask_question'
    post 'generate_recipe', to: 'change#generate_recipe'
    get 'show_recipe', to: 'change#show_recipe'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    skip_before_action :require_login
    def top; end

    def explanation; end

    def privacy; end

    def condition; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/condition.html.erb
<div class="container mt-5">
  <h1 class="mb-4 font-weight-bold text-center">利用規約</h1>

  <div class="alert alert-success" role="alert">
  <p class="mb-0">
    この利用規約（以下、「本規約」といいます。）は、本サービス（本サイトを含むものとし、以下、特に両者を区別しません。）の利用条件を定めるものです。
  </p>
</div>
  <div class="card mb-4">
    <div class="card-header">
        <h4 id="section1">第1条（適用）</h4>
        <div class="card-body">
          <div class="mb-3">
            <h5 class="font-weight-bold">本規約の適用範囲</h5>
            <p>本規約は、ユーザーと本サービスの利用に関わるすべての関係に適用されます。</p>
          </div>
          <div class="mb-3">
            <h5 class="font-weight-bold">個別規定の適用</h5>
            <p>本サービスの提供にあたり、本規約に加えて、特定の利用ルールやガイドラインなどの個別規定（以下、「個別規定」といいます。）を定めることがあります。</br>これらの個別規定は、その名称に関わらず、本規約の一部を構成し、本規約と同等に適用されます。</p>
          </div>
          <div class="mb-3">
            <h5 class="font-weight-bold">規約の優先順位</h5>
            <p>本規約と個別規定が矛盾する場合、個別規定が特に異なる定めをしている場合を除き、個別規定の内容が優先されます。</p>
          </div>
        </div>
    </div>
  </div>
  
  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section2">第2条（利用登録）</h4>
        <div class="card-body">
          <div class="mb-3">
            本サービスにおいては，登録希望者が本規約に同意の上，当サイトの定める方法によって利用登録を申請し，当サイトがこれを承認することによって，利用登録が完了するものとします。</br>
            利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
            <ul>
              <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
              <li>本規約に違反したことがある者からの申請である場合</li>
              <li>その他，当サイトが利用登録を相当でないと判断した場合</li>
            </ul>
          </div>
        </div>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section3">第3条（ユーザーIDおよびパスワードの管理）</h4>
        <div class="card-body">
          <div class="mb-3">
            <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</p>
            ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。</br>当サイトは，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。
            ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当サイトに故意又は重大な過失がある場合を除き，当サイトは一切の責任を負わないものとします。
          </div>
        </div>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section4">第4条（利用料金および支払方法）</h4>
        本サービスは、すべての機能を無料で提供しています。利用料金に関する規定は適用されません。
    </div>
  </div>
  
  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section5">第5条（禁止事項）</h4>
        <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
        <ul>
          <li>法令または公序良俗に違反する行為</li>
          <li>犯罪行為に関連する行為</li>
          <li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
          <li>当サイト，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
          <li>本サービスによって得られた情報を商業的に利用する行為</li>
          <li>本サービスの運営を妨害するおそれのある行為</li>
          <li>不正アクセスをし，またはこれを試みる行為</li>
          <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
          <li>不正な目的を持って本サービスを利用する行為</li>
          <li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
          <li>他のユーザーに成りすます行為</li>
          <li>当サイトが許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
          <li>面識のない異性との出会いを目的とした行為</li>
          <li>当サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
          <li>その他，当サイトが不適切と判断する行為</li>
        </ul>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section6">第6条（本サービスの提供の停止等）</h4>
        <p>当サイトは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
          <ul>
            <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
            <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
            <li>コンピュータまたは通信回線等が事故により停止した場合</li>
            <li>その他，本サービスの提供が困難と判断した場合</li>
          </ul>
        <p>本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</p>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section7">第7条（利用制限および登録抹消）</h4>
        <p>当サイトは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</p>
          <ul>
            <li>本規約のいずれかの条項に違反した場合</li>
            <li>登録事項に虚偽の事実があることが判明した場合</li>
            <li>本サービスの利用を適当でないと判断した場合</li>
          </ul>
        <p>当サイトは，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
    </div>
  </div>
      
  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section8">第8条（退会）</h4>
        <p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
    </div>
  </div>
      
  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section9">第9条（保証の否認および免責事項）</h4>
        <p>当サイトは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</p>
        当サイトは，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。</br>ただし，本サービスに関する当サイトとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</br>
        前項ただし書に定める場合であっても，当サイトは，当サイトの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当サイトまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。</br>
        <p>当サイトは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>
    </div>
  </div>
     
  <div class="card mb-4">
    <div class="card-header">
      <h4 id="section10">第10条（サービス内容の変更等）</h4>
        当サイトは，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">     
      <h4 id="section11">第11条（利用規約の変更）</h4>
        <p>当サイトは以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</p>
          <ul>
            <li>本規約の変更がユーザーの一般の利益に適合するとき。</li>
            <li>本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
          </ul>
        <p>当サイトはユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</p>
    </div>
  </div>
     
  <div class="card mb-4">
    <div class="card-header">     
      <h4 id="section12">第12条（個人情報の取扱い）</h4>
        当サイトは，本サービスの利用によって取得する個人情報については，<%= link_to "プライバシーポリシー", privacy_policy_path %>に従い適切に取り扱うものとします。
    </div>
  </div>
       
  <div class="card mb-4">
    <div class="card-header">     
      <h4 id="section13">第13条（通知または連絡）</h4>
        ユーザーと当サイトとの間の通知または連絡は，当サイトの定める方法によって行うものとします。当サイトは,ユーザーから,当サイトが別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">     
      <h4 id="section14">第14条（権利義務の譲渡の禁止）</h4>
        ユーザーは，当のサイト書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">     
      <h4 id="section15">第15条（準拠法・裁判管轄）</h4>
        本規約の解釈にあたっては，日本法を準拠法とします。
        本サービスに関して紛争が生じた場合には，当サイトの所在地を管轄する裁判所を専属的合意管轄とします。
    </div>
  </div>
      
  <h4>以上</h4>
</div>

app/views/static_pages/explanation.html.erb
<div class="container mt-5">
  <div class="section-header text-center mb-4">
      <p class="mb-2 d-block fs-5">このアプリは、アレルギーや、食べられない食材がある方向けに作成しました。</p>
      <p class="mb-0 d-block fs-5">以下の手順に従って、レシピの分量を入力し、変換する材料を指定することで、指定した材料を使用しない新しいレシピを生成できます。</p>
    </div>
    <h3 class="text-center mt-5 mb-3 d-block">使い方</h3>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <ol class="list-unstyled mb-4">
            <li class="mb-4">
              <strong class="d-block fs-4">①レシピの分量を入力</strong>
              <p>作りたいレシピの分量を入力してください。</p>
              <div class="mb-4">
                <label class="form-label">例:プリンを作成したい場合</label>
                <div class="p-3 bg-success text-white rounded text-center">
                  <div class="mb-2">「レシピの分量」欄に下記を入力</div>
                  <div class="fw-bold">卵2個<br>牛乳300cc<br>砂糖70g</div>
                </div>
              </div>
            </li>
            <li class="mb-4">
              <strong class="d-block fs-4">②変換する材料を指定</strong>
              <p>レシピに使用したくない材料を指定します。</p>
              <p>これにより、その材料を含まないレシピを新しく生成します。</p>
              <div class="mb-4">
                <label class="form-label">例:卵アレルギーのため、卵を使用したくない</label>
                <div class="p-3 bg-success text-white rounded text-center">
                  <div class="mb-2">「変換材料」欄に下記を入力</div>
                  <div class="fw-bold">卵</div>
                </div>
              </div>
            </li>
            <li>
              <strong class="d-block fs-4">③新しいレシピを生成</strong>
              <div class="text-center mt-4">
                <button class="btn btn-success" type="button">変換</button>
                <div class="mt-2">ボタンをクリックすると、指定された材料を使用しない、新しいレシピが生成されます</div>
              </div>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="p-4 d-flex flex-column justify-content-center">
  <div class="container text-center">
    <%= link_to "使ってみる", openai_ask_question_path, class: "btn btn-warning text-dark btn-lg me-3" %>
  </div>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<div class="container mt-5">
  <h2 class="mb-4 font-weight-bold text-center">プライバシーポリシー</h2>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">お客様から取得する情報</h5>
    </div>
    <div class="card-body">
      <ul>
        <li>氏名（ニックネームやペンネームも含む）</li>
        <li>性別</li>
        <li>メールアドレス</li>
      </ul>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">お客様の情報を利用する目的</h5>
    </div>
    <div class="card-body">
      <ul>
        <li>当サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当サービスの利用履歴を管理するため</li>
        <li>当サービスに関するご案内をするため</li>
        <li>お客様からのお問い合わせに対応するため</li>
        <li>当サイトの規約や法令に違反する行為に対応するため</li>
        <li>当サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
        <li>当サイト規約の変更等を通知するため</li>
        <li>以上の他、当サービスの提供、維持、保護及び改善のため</li>
      </ul>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">安全管理のために講じた措置</h5>
    </div>
    <div class="card-body">
      <p>
        当サイトは、お客様から取得した情報について、適切なセキュリティ対策を講じています。</br>具体的には、データの暗号化、アクセス制限、定期的なセキュリティチェックなどを実施しています。</br>詳細な措置については、法令に基づき個別にご回答いたします。
      </p>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">第三者提供</h5>
    </div>
    <div class="card-body">
      <p>
        当サイトは、お客様から取得する情報のうち、個人データ（個人情報保護法第16条第3項）に該当するものについては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
      </p>
      <p>但し、次の場合は除きます。</p>
      <ul>
        <li>個人データの取扱いを外部に委託する場合</li>
        <li>当社サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">プライバシーポリシーの変更</h5>
    </div>
    <div class="card-body">
      <p>
        当サイトは、必要に応じて、このプライバシーポリシーの内容を変更します。</br>変更後のプライバシーポリシーについては、ウェブサイト上に掲示する方法などで周知いたします。
      </p>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <h5 class="mb-0">お問い合わせ</h5>
    </div>
    <div class="card-body">
      <p>
        お客様の情報の開示、訂正、利用停止、削除をご希望の場合は、以下のメールアドレスにご連絡ください。
      </p>
      <p>
        e-mail: <a href="mailto:mika.cookswap@gmail.com">mika.cookswap@gmail.com</a>
      </p>
      <p>
        この際、運転免許証等当社が指定する方法により、ご本人確認をさせていただきます。情報の開示請求には、申請時に1件あたり1,000円の事務手数料がかかります。
      </p>
    </div>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

app/views/static_pages/top.html.erb
<% content_for(:title, t('.title')) %>
<div class="top-wrapper text-white text-center py-5">
  <div class="container">
    <div class="mb-4">
      <%= image_tag 'logo.png', alt: t("header.toppage"), width: 400, class: 'mb-5' %>
    </div>
  </div>
  <%= link_to "このサイトの使い方", explanation_path, class: "btn btn-warning btn-lg text-orange me-3" %>

</div>

<div class="bg-warning text-white py-5">
  <div class="container text-center">
    <%= link_to t('openai.change.ask_question.title'), openai_ask_question_path, class: "btn btn-light btn-lg text-orange me-3" %>
    <%= link_to t('recipes.index.title'), recipes_path, class: "btn btn-light btn-lg text-orange" %>
  </div>
</div>