config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "static_pages#top"
  get "explanation", to: "static_pages#explanation"
  get "privacy_policy", to: "static_pages#privacy"
  get "terms_of_service", to: "static_pages#condition"

  resources :contacts, only: [:new, :create]
  
  get 'user_top', to: 'homes#top'

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resource :profile, only: %i[edit update show]
  resources :recipes, only: %i[index new create edit show update destroy] do
    collection do
      get :create_index
    end
  end
  namespace :openai do
    get 'ask_question', to: 'change#ask_question'
    post 'generate_recipe', to: 'change#generate_recipe'
    get 'show_recipe', to: 'change#show_recipe'
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :process, presence: true
  enum genre: { japanese: 0, chinese: 1, western: 2, sweets: 3, other: 4}
  enum release: { in: 0, out: 1}

  has_many :recipe_materials, dependent: :destroy
  has_many :materials, through: :recipe_materials
  belongs_to :user

  def self.ransackable_associations(auth_object = nil)
    ["materials", "recipe_materials", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "materials.name"]
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true)
                .joins(:recipe_materials, :materials)
                .where(release: Recipe.releases[:in])
                .includes(:user).order(created_at: :desc)
                .page(params[:page])
  end

  def create_index
    @recipes = current_user.recipes.page(params[:page])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.process = params[:process] if params[:process]
    @materials = params[:materials].to_s.split("\n") if params[:materials]
  end
    
  def create
    Rails.logger.debug "Params creation_steps: #{params[:creation_steps].inspect}"
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.process = params[:process] if params[:process].present?  # @creation_stepsを結合してprocessに保存
    if @recipe.save
      save_materials(@recipe)
      redirect_to recipes_path
      flash[:success] = t('defaults.flash_message.created_recipe')
    else
      flash.now[:danger] = t('defaults.flash_message.not_created_recipe')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = t('defaults.flash_message.updated_recipe')
      redirect_to create_index_recipes_path(@recipe)
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated_recipe')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy!
    redirect_to recipes_path, success: t('defaults.flash_message.deleted_recipe'), status: :see_other
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :process, :genre, :release, :gender, :created_at)
  end

  def save_materials(recipe)
    materials_list = parse_materials(params[:materials])
    existing_materials, new_materials = categorize_materials(materials_list)

    new_material_ids = save_new_materials(new_materials)
    create_recipe_materials(recipe, existing_materials.merge(new_material_ids.index_by { |m| m[:id] }))
  end
  
  def parse_materials(materials_text)
    materials_text.split("\n").map do |line|
      line.gsub(/[-：]/, '').strip
    end.reject(&:empty?)
  end

  def categorize_materials(materials_list)
    existing_materials = {}
    new_materials = []
  
    materials_list.each do |material|
      material_name = divide_material_names([material]).first
      volume, scale = divide_volume_and_scale(material)
  
      next unless material_name.present?
  
      if (existing_material = Material.find_by(name: material_name.strip))
        existing_materials[existing_material.id] = { volume: volume, scale: scale }
      else
        new_materials << { name: material_name, volume: volume, scale: scale }
      end
    end
  
    [existing_materials, new_materials]
  end
  
  def save_new_materials(new_materials)
    new_material_ids = []
  
    new_materials.each do |material_data|
      new_material = Material.create(name: material_data[:name])
      new_material_ids << { id: new_material.id, volume: material_data[:volume], scale: material_data[:scale] }
    end
  
    new_material_ids
  end

  def create_recipe_materials(recipe, materials)
    materials.each do |material_id, attributes|
      Rails.logger.debug "Creating RecipeMaterial: recipe_id=#{recipe.id}, material_id=#{material_id}, volume=#{attributes[:volume]}, scale=#{attributes[:scale]}"
      RecipeMaterial.create(
        recipe_id: recipe.id,
        material_id: material_id,
        volume: attributes[:volume],
        scale: attributes[:scale]
      )
    end
  end
  
  def divide_material_names(materials)
    materials.map do |material|
      match = material.match(/^(?<name>[^0-9]+)\s*(?<volume>\d+)?\s*(?<unit>\w+)?$/)
      match ? match[:name].strip : material
    end
  end
  
  def divide_volume_and_scale(material)
    if material =~ /(\d+)\s*(\D+)$/
      volume = $1
      scale = $2.strip
    else
      volume = nil
      scale = nil
    end
    [volume, scale]
  end
  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, class: "needs-validation", local: true, turbo: false do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', id: 'recipe_title' %>
  </div>
  <div class="form-group">
    <%= f.label :genre, class: "form-label" %>
    <%= f.select :genre, Recipe.genres_i18n.invert, { include_blank: "ジャンルを選択してください" }, class: 'form-control', id: 'recipe_genre' %>
  </div>
  <div class="form-group">
    <%= f.label :process, class: "form-label" %>
    <%= f.text_area :process, class: 'form-control', id: 'recipe_process', rows: 10 %>
  </div>
  <div class="form-group">
    <%= f.label :release, class: "form-label" %>
    <%= f.select :release, Recipe.releases_i18n.invert, {}, class: 'form-control', id: 'recipe_release' %>
  </div>
  <div class="text-center mt-4">
    <%= f.submit nil, class: 'btn btn-success mt-2' %>
    <%= link_to t('recipes.index.title'), recipes_path, class: "btn btn-secondary mt-2" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="recipe-id-<%= recipe.id %>" class="card bg-warning-light border-warning rounded">
    <div class="card-body">
      <div class="d-flex align-items-center justify-content-between">
        <h4 class="card-title mb-0 me-3">
          <%= link_to recipe.title, recipe_path(recipe), class: "text-dark text-decoration-none" %>
        </h4>
        <% if current_user && current_user.own?(recipe) %>
          <div class="btn-group ms-auto">
            <%= link_to edit_recipe_path(recipe), id: "button-edit-#{recipe.id}", class: "btn btn-warning btn-sm text-white" do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
            <%= link_to recipe_path(recipe), id: "button-delete-#{recipe.id}", class: "btn btn-danger btn-sm text-white", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      <ul class="list-inline mt-2 mb-0">
        <li class="list-inline-item text-muted"><i class="bi bi-person"></i><%= recipe.user&.name || 'Unknown User' %></li>
        <li class="list-inline-item text-muted"><i class="bi bi-tag"></i> <%= Recipe.genres_i18n[recipe.genre] %></li>
        <li class="list-inline-item text-muted"><i class="bi bi-calendar"></i><%= l recipe.created_at, format: :short %></li>
      </ul>
    </div>
  </div>
</div>

app/views/recipes/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="d-flex w-auto input-group mb-3">
    <%= f.search_field :title_cont, placeholder: 'タイトル', class: 'form-control' %>
    <%= f.search_field :materials_name_cont, placeholder: '材料名', class: 'form-control' %>
    <div class="input-group-append">
      <%= f.submit t('helpers.submit.search'), class: 'btn btn-outline-success' %>
    </div>
  </div>
<% end %>

app/views/recipes/create_index.html.erb
<div class="d-flex flex-column min-vh-100">
  <div class="container flex-grow-1">
    <div class="row">
    <h1 class="text-center mb-4"><%= t('.title') %></h1>
      <% @recipes.each do |recipe| %>
        <div class="col-sm-12 col-lg-4 mb-4">
          <div class="card bg-light border-warning rounded shadow-sm h-100">
            <div class="card-body d-flex flex-column">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <h4 class="card-title mb-0">
                  <%= link_to recipe.title, recipe_path(recipe), class: "text-dark" %>
                </h4>
                <div class="btn-group">
                  <%= link_to edit_recipe_path(recipe), id: "button-edit-#{recipe.id}", class: "btn btn-warning btn-sm text-white" do %>
                    <i class="bi bi-pencil-fill"></i>
                  <% end %>
                  <%= link_to recipe_path(recipe), id: "button-delete-#{recipe.id}", class: "btn btn-danger btn-sm text-white", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                    <i class="bi bi-trash-fill"></i>
                  <% end %>
                </div>
              </div>
              <% if recipe.in? %>
                <div class="mb-3">
                  <span class="badge bg-success">投稿済</span>
                </div>
              <% end %>
              <ul class="list-inline mb-0 mt-auto">
                <li class="list-inline-item text-muted"><i class="bi bi-tag"></i> <%= Recipe.genres_i18n[recipe.genre] %></li>
                <li class="list-inline-item"><i class="bi bi-calendar"></i> <%= l recipe.created_at, format: :short %></li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @recipes, theme: 'bootstrap-5' %>
  </div>

app/views/recipes/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="d-flex flex-column min-vh-100">
  <div class="container pb-4">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6">
        <h1 class="text-center mb-4"><%= t('.title') %></h1>
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="d-flex flex-column min-vh-100">
  <div class="container pt-3">
    <div class="row">
      <h1 class="text-center mb-4"><%= t('.title') %></h1>
        <div class="col-lg-10 offset-lg-1">
          <%= render 'search_form', q: @q, url: recipes_path %>
        </div>
    </div>
      <div class="row">
        <div class="col-12" >
          <div class="row">
            <% if @recipes.present? %>
              <%= render @recipes %>
            <% else %>
              <p>ありません</p>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <%= paginate @recipes,theme: 'bootstrap-5'%>
</div>

app/views/recipes/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="d-flex flex-column min-vh-100">
  <div class="container pb-4">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6">
        <h1 class="text-center mb-4"><%= t('.title') %></h1>
        <%= form_with(model: @recipe, local: true, turbo: false ,class: "needs-validation") do |f| %>
          <div class="mb-3">
            <%= f.label :title %>
            <%= f.text_field :title, value: @recipe.title %>
          </div>
          <div class="mb-3">
            <%= f.label :genre, class: "form-label" %>
            <%= f.select :genre, Recipe.genres_i18n.invert, { include_blank: "ジャンルを選択してください" }, class: 'form-control', id: 'recipe_genre' %>
          </div>
          <div class="mb-3">
            <%= f.label :materials, "材料", class: "form-label" %>
            <%= text_area_tag :materials, params[:materials], rows: 5, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :process, "作り方", class: "form-label" %>
            <%= f.text_area :process, rows: 5, class: "form-control" , id: 'recipe_process' %>
          </div>
          <div class="mb-3">
            <%= f.label :release, class: "form-label" %>
            <%= f.select :release, Recipe.releases_i18n.invert, {}, class: 'form-control', id: 'recipe_release' %>
          </div>
          <div class="text-center mt-4">
            <%= f.submit nil, class: "btn btn-success" %>
            <%= link_to t('recipes.index.title'), recipes_path, class: "btn btn-outline-secondary" %>
          </div>
        <% end %>        
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% content_for(:title, "#{@recipe.title}") %>
<div class="container pt-5">
  <div class="row mb-4">
    <div class="col-lg-8 offset-lg-2">
      <h1 class="mb-4 text-center font-weight-bold">レシピ詳細</h1>
      <article class="card bg-warning-light border-warning rounded"> <!-- Added border-orange class -->
        <div class="card-body">
          <div class="row">
            <div class="col-md-9 mb-3 mb-md-0">
              <h3 class="d-inline mb-2 font-weight-bold"><%= @recipe.title %></h3>
              <div class="d-flex justify-content-end align-items-center">
                <% if current_user && current_user.own?(@recipe) %>
                  <%= link_to edit_recipe_path(@recipe), id: "button-edit-#{@recipe.id}", class: "btn btn-warning btn-sm text-white me-2" do %>
                    <i class='bi bi-pencil-fill'></i> <%= t("helpers.submit.edit")%>
                  <% end %>
                  <%= link_to recipe_path(@recipe), data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, id: "button-delete-#{@recipe.id}", class: "btn btn-danger btn-sm text-white" do %>
                    <i class="bi bi-trash-fill"></i> <%= t("helpers.submit.delete")%>
                  <% end %>
                <% end %>
              </div>
              <ul class="list-inline mt-2">
                <li class="list-inline-item text-muted"><i class="bi bi-person"></i> <%= @recipe.user.name %></li>
                <li class="list-inline-item text-muted"><i class="bi bi-calendar"></i> <%= l @recipe.created_at, format: :long %></li>
              </ul>
            </div>
          </div>
          <% if @recipe.recipe_materials.any? %>
            <h4 class="mt-4 mb-2 font-weight-bold">材料</h4>
            <ul class="list-unstyled">
              <% @recipe.recipe_materials.each do |recipe_material| %>
                <li>
                  <% if recipe_material.material %>
                    <strong><%= recipe_material.material.name %></strong>
                  <% end %>
                  <% if recipe_material.volume.present? && recipe_material.scale.present? %>
                    <span class="text-muted"><%= recipe_material.volume %> <%= recipe_material.scale %></span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p class="text-muted">材料が設定されていません。</p>
          <% end %>
          <h4 class="mt-4 font-weight-bold">作り方</h4>
          <p><%= simple_format(@recipe.process) %></p>
        </div>
      </article>
      <div class="text-center mt-4">
        <%= link_to t('recipes.index.title'), recipes_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>