config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "static_pages#top"
  get "explanation", to: "static_pages#explanation"
  get "privacy_policy", to: "static_pages#privacy"
  get "terms_of_service", to: "static_pages#condition"

  resources :contacts, only: [:new, :create]
  
  get 'user_top', to: 'homes#top'

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resource :profile, only: %i[edit update show]
  resources :recipes, only: %i[index new create edit show update destroy] do
    collection do
      get :create_index
    end
  end
  namespace :openai do
    get 'ask_question', to: 'change#ask_question'
    post 'generate_recipe', to: 'change#generate_recipe'
    get 'show_recipe', to: 'change#show_recipe'
  end

end

app/views/shared/_before_login_header.html.erb
<div class="d-flex justify-content-end align-items-center bg-light py-3 px-4 shadow-sm">
  <div class="me-3">
    <%= link_to t("header.login"), login_path, class: "btn btn-outline-success" %>
  </div>
  <div class="me-3">
    <%= link_to t("header.register"), new_user_path, class: "btn btn-outline-success" %>
  </div>
  <div class="ms-auto d-flex align-items-center">
    <%= link_to t("static_pages.top.title"), root_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-secondary text-white">
  <div class='container py-4'>
    <div class='row'>
      <div class='col-12'>
        <div class="d-flex flex-column">
          <div class="mb-2">
            <%= link_to t("footer.contact_us"), new_contact_path, class: 'text-light d-block' %>
          </div>
          <div class="mb-2">
            <%= link_to t("footer.terms_of_service"), terms_of_service_path, class: 'text-light d-block' %>
          </div>
          <div class="mb-2">
            <%= link_to t("footer.privacy_policy"), privacy_policy_path, class: 'text-light d-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="d-flex justify-content-between align-items-center">
  <% if logged_in? %>
    <%= link_to user_top_path do %>
      <%= image_tag 'logo.png', alt: t("header.toppage"), width: 100 %>
    <% end %>
    
    <div class="d-flex align-items-center">
      <div class="btn" data-bs-toggle="offcanvas" href="#offcanvasID" role="button" aria-controls="offcanvasID">
        <i class="bi  bi-list fs-4" style="color: #FF5733;">
          <%= render 'shared/sidebar'%>
        </i>
      </div>
    </div>
  <% else %>
    <%= link_to t("header.toppage"), root_path, class: '' %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="offcanvas offcanvas-end bg-light" tabindex="-1" id="offcanvasID" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header border-bottom">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel"><%= current_user.name %>さんのメニュー</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="mb-3">
      <%= link_to t("sidebar.profile"), profile_path, class: "btn btn-outline-success w-100 text-start" %>
    </div>
    <div class="mb-3">
      <%= link_to t("recipes.create_index.title"), create_index_recipes_path, class: "btn btn-outline-success w-100 text-start" %>
    </div>
    <div>
      <%= link_to t("sidebar.logout"), logout_path, class: "btn btn-outline-secondary w-100 text-start", data: { turbo_method: :delete } %>
    </div>
  </div>
</div>